#ifndef CAIRO_FEATURES_H
#define CAIRO_FEATURES_H

#define CAIRO_HAS_FC_FONT 0
#define CAIRO_HAS_FT_FONT 0
#define CAIRO_HAS_GOBJECT_FUNCTIONS 0
#define CAIRO_HAS_IMAGE_SURFACE 1
#define CAIRO_HAS_MIME_SURFACE 1
#define CAIRO_HAS_OBSERVER_SURFACE 1
#define CAIRO_HAS_PDF_SURFACE 1
#define CAIRO_HAS_PNG_FUNCTIONS 1
#define CAIRO_HAS_PS_SURFACE 1
#define CAIRO_HAS_RECORDING_SURFACE 1
#define CAIRO_HAS_SCRIPT_SURFACE 1
#define CAIRO_HAS_SVG_SURFACE 1
#define CAIRO_HAS_USER_FONT 1
#define CAIRO_HAS_XCB_SHM_FUNCTIONS 1
#define CAIRO_HAS_XCB_SURFACE 1
#define CAIRO_HAS_XLIB_SURFACE 1
#define CAIRO_HAS_XLIB_XRENDER_SURFACE 1

#define HAVE_X11_EXTENSIONS_SHMPROTO_H 1
#define HAVE_X11_EXTENSIONS_SHMSTR_H 1
#define HAVE_X11_EXTENSIONS_XSHM_H 1
#define HAVE_XRENDERCREATECONICALGRADIENT 1
#define HAVE_XRENDERCREATELINEARGRADIENT 1
#define HAVE_XRENDERCREATERADIALGRADIENT 1
#define HAVE_XRENDERCREATESOLIDFILL 1
#define HAVE_ZLIB 1

#endif
